name: Makefile CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make
      
    - name: zipppp...
      run: make archive
